feat(ChainSelect): wip: main functions of ChainSelect
Conflux-Chain/rigel pull request #31
Opened 2021-05-31 06:56 UTC by zctocm

2021-05-31 07:11 UTC, angelia-yuqi-personal requested changes

2021-05-31 07:11 UTC, angelia-yuqi-personal commented on src/pages/Shuttle/index.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
why use react-hooks/exhaustive-deps, may need to add `setFromChain` and `setToChain`

2021-05-31 07:11 UTC, angelia-yuqi-personal commented on src/pages/components/ChainSelect/index.js
> +function getChainsData(type, chain, fromChain) {
can use a data hook

2021-06-01 02:29 UTC, zctocm commented on src/components/MenuItem/index.js
> +} from '../../assets/images'
done

2021-06-01 02:29 UTC, zctocm commented on src/pages/Shuttle/index.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
done

2021-06-01 02:30 UTC, zctocm commented on src/pages/components/ChainSelect/index.js
> +function getChainsData(type, chain, fromChain) {
done

2021-06-01 05:30 UTC, angelia-yuqi-personal approved these changes

2021-06-01 06:01 UTC, merged