fix: refactor object and array dependences
Conflux-Chain/rigel pull request #70
Opened 2021-06-30 10:12 UTC by angelia-yuqi-personal

2021-06-30 13:54 UTC, yqrashawn requested changes

2021-06-30 13:54 UTC, yqrashawn commented on src/hooks/useAddTokenToMetamask.js
> +import {convertJsonToString} from '../utils'
Please remove this function and examine the deps one by one.

2021-06-30 13:54 UTC, yqrashawn commented on src/hooks/useAddTokenToMetamask.js
> +  }, [convertJsonToString(library), convertJsonToString(token)])
For example, the `library` can only be `undefined` or string.
And we can use `token.address` here instead of stringify the token.
If the address is not the only identifier of the token, we can combine multiple identifiers together.

2021-06-30 13:54 UTC, yqrashawn commented on src/hooks/usePortal.js
> +  }, [address, convertJsonToString(error), portalInstalled])
Just use `Boolean(error)` here since we only cares about its existence and it won't be things like `0` or `''`.

2021-06-30 13:54 UTC, yqrashawn commented on src/hooks/usePortal.js
> +  }, [address, convertJsonToString(ABI), convertJsonToString(confluxJS)])
remove the abi one since same address won't have different abi
use Boolean(confluxJS) since it won't be changed once created

2021-06-30 14:04 UTC, angelia-yuqi-personal commented on src/hooks/useAddTokenToMetamask.js
> +  }, [convertJsonToString(library), convertJsonToString(token)])
do you mean the `library` can only be `undefined` or string? But I think it is a object.

2021-07-01 02:45 UTC, angelia-yuqi-personal commented on src/hooks/useAddTokenToMetamask.js
> +import {convertJsonToString} from '../utils'
done

2021-07-01 02:45 UTC, angelia-yuqi-personal commented on src/hooks/useAddTokenToMetamask.js
> +  }, [convertJsonToString(library), convertJsonToString(token)])
done

2021-07-01 02:46 UTC, angelia-yuqi-personal commented on src/hooks/usePortal.js
> +  }, [address, convertJsonToString(error), portalInstalled])
done

2021-07-01 02:46 UTC, angelia-yuqi-personal commented on src/hooks/usePortal.js
> +  }, [address, convertJsonToString(ABI), convertJsonToString(confluxJS)])
done

2021-07-01 03:16 UTC, yqrashawn requested changes

2021-07-01 03:16 UTC, yqrashawn commented on src/hooks/useShuttleData.js
> +    isCfxChain,
duplicate with the first dep

2021-07-01 03:16 UTC, yqrashawn commented on src/hooks/useShuttleData.js
> +    [in_fee.toString(), isToChainCfx, out_fee.toString()],
no need to use `useMemo` here. there's little difference in the computation

and why return different data type here, number 0 and toString(10)

2021-07-01 03:23 UTC, angelia-yuqi-personal commented on src/hooks/useShuttleData.js
> +    isCfxChain,
done

2021-07-01 03:39 UTC, zctocm commented on src/hooks/useShuttleData.js
> +    [in_fee.toString(), isToChainCfx, out_fee.toString()],
done

2021-07-01 03:42 UTC, yqrashawn approved these changes

2021-07-01 04:05 UTC, zctocm approved these changes

2021-07-01 04:05 UTC, merged